const user = {
  rank: 17,
  running_total: {
    daily_average: 37709,
    human_readable_daily_average: "10 hrs 28 mins",
    human_readable_total: "73 hrs 19 mins",
    languages: [
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
    ],
    languages_html:
      '<a href="https://wakatime.com/leaders/language/rust">Rust</a>, <a href="https://wakatime.com/leaders/language/toml">TOML</a>, <a href="https://wakatime.com/leaders/language/csv">CSV</a>, <a href="https://wakatime.com/leaders/language/c%2B%2B">C++</a>, <a href="https://wakatime.com/leaders/language/text">Text</a>, <a href="https://wakatime.com/leaders/language/javascript">JavaScript</a>, <a href="https://wakatime.com/leaders/language/python">Python</a>, <a href="https://wakatime.com/leaders/language/perl">Perl</a>, <a href="https://wakatime.com/leaders/language/csv/tsv">CSV/TSV</a>, …',
    total_seconds: 263966.152606,
  },
  user: {
    city: {
      ascii_name: "Los Angeles",
      ascii_state: "California",
      country: "United States",
      country_code: "US",
      id: "16a54cb1-de5e-42ce-833b-f236d93de220",
      name: "Los Angeles",
      population: 3898747,
      short_title: "Los Angeles, CA",
      state: "California",
      timezone: "America/Los_Angeles",
      title: "Los Angeles, California",
      title_including_country: "Los Angeles, California, United States",
    },
    display_name: "Tony Kan",
    email: null,
    full_name: "Tony Kan",
    human_readable_website: "",
    id: "832fa69c-93f3-414f-b372-c2853994ef03",
    is_email_public: true,
    is_hireable: true,
    location: null,
    photo: "https://wakatime.com/photo/832fa69c-93f3-414f-b372-c2853994ef03",
    photo_public: true,
    username: "tkanx",
    website: "",
  },
};
